recipes/urls.py
from django.urls import path

from recipes import views


urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('<int:pk>', views.RecipeDetail.as_view(), name='recipe-detail'),
    path('<int:pk>/update', views.EditRecipe.as_view(), name='recipe-edit'),
    path('add', views.AddRecipe.as_view(), name='recipe-add'),

    path('ingredients', views.IngredientList.as_view(), name='ingredients'),
    path('ingredients/<int:pk>', views.IngredientDetail.as_view(), name='ingredient-detail'),
    path('ingredients/<int:pk>/update', views.EditIngredient.as_view(), name='ingredient-edit'),
    path('ingredients/add', views.AddIngredient.as_view(), name='ingredient-add')
]

recipes/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse


class Ingredient(models.Model):
    GRAM = 'gram'
    LITER = 'liter'
    FACTOR_GRAM_TO_KG = 1000
    FACTOR_LITER_TO_CL = 1 / 100
    
    UNITS = (
        (GRAM, '1 gram'),
        (LITER, '1 liter')
    )

    name = models.CharField(max_length=255)
    article_number = models.TextField(blank=True, null=True)
    cost = models.DecimalField(
        max_digits=12, decimal_places=4, default=0)
    
    unit = models.CharField(max_length=20, choices=UNITS)
    
    xukezheng = models.CharField(max_length=255,null=True,blank=True)
    biaozhun = models.CharField(max_length=255, null=True,blank=True)
    baozhi = models.DateField(null=True,blank=True)
    chandi = models.CharField(max_length=255, null=True,blank=True)
    chengfen = models.CharField(max_length=255, null=True,blank=True)
    def __str__(self):
        return f'{self.name} ({self.unit})'

    def get_absolute_url(self):
        return reverse('ingredient-detail', kwargs={'pk': self.pk})
    
    def get_unit_for_display(self):
        if self.unit == self.GRAM:
            return "grams"
        else:
            return "liters"

    def get_units(self):
        units = []
        _base = {
            'unit': self.unit,
            'cost': self.cost
        }
        if self.unit == self.GRAM:
            units.append(_base)
            units.append({
                'unit': 'kilo gram',
                'cost': round(self.cost * Decimal(self.FACTOR_GRAM_TO_KG), 4)
            })
        else:
            units.append({
                'unit': 'centiliter',
                'cost': round(self.cost * Decimal(self.FACTOR_LITER_TO_CL), 4)
            })
            units.append(_base)
        return units



class Recipe(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'pk': self.pk})

    def get_cost(self):
        cost_ingds = [i.get_cost() for i in self.ingredients.all()]
        return sum(cost_ingds)

    def count_ingredients(self):
        return self.ingredients.count()

    def get_initials(self):
        words = self.name.split()
        return "".join([w[0].upper() for w in words])


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients")
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='recipes')
    quantity = models.FloatField(default=0)
    
    def __str__(self):
        return f'{self.ingredient} in {self.recipe}'

    def get_cost(self):
        return self.ingredient.cost * Decimal(self.quantity)

recipes/forms.py
from decimal import Decimal

from django import forms
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, Submit

from recipes.custom_layout import Formset
from recipes.models import Ingredient, Recipe, RecipeIngredient


CHOICES = (
    (Ingredient.GRAM, '1 克'),
    (Ingredient.LITER, '1 升'),
    ('kilogram', '1 千克'),
    ('centiliter', '1 毫升')
)

FORMSET_NAME = 'ingredients'


class IngredientForm(forms.ModelForm):
    unit = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Ingredient
        exclude = ()

    def save(self, commit=True):
        obj = super().save(commit=False)

        cleaned_data = self.cleaned_data
        cost = cleaned_data['cost']
        unit = cleaned_data['unit']

        if unit == 'kilogram':
            factor = Ingredient.FACTOR_GRAM_TO_KG
            unit = 'gram'
        elif unit == 'centiliter':
            factor = Ingredient.FACTOR_LITER_TO_CL
            unit = 'liter'
        else:
            factor = 1
        cost = cost / Decimal(factor)
        obj.cost = round(cost, 4)
        obj.unit = unit
        if commit:
            obj.save()
        return obj


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        exclude = ()


IngredientsFormSet = inlineformset_factory(
    Recipe, RecipeIngredient, form=RecipeIngredientForm, extra=1, can_delete=True)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('name'),
                Field('description'),
                Fieldset('Add ingredients',
                    Formset(FORMSET_NAME)),
                HTML("<br>"),
                Submit('submit', '保存食谱', css_class="btn-primary bg-rm-main my-3"),
                )
            )

recipes/views.py
from django.db import transaction
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from recipes import models
from recipes.forms import FORMSET_NAME, IngredientForm, IngredientsFormSet, RecipeForm


class RecipeList(ListView):
    model = models.Recipe
    template_name = 'home.html'
    context_object_name = 'recipes'
    ordering = ['name']


class RecipeDetail(DetailView):
    queryset = models.Recipe.objects.prefetch_related('ingredients__ingredient')
    template_name = 'recipes/detail.html'


class IngredientList(ListView):
    template_name = 'ingredients/list.html'
    model = models.Ingredient

    def get_queryset(self):
        q = self.request.GET.get('q', '')
        object_list = self.model.objects.order_by('name')
        if q:
            _objs_name = object_list.filter(name__icontains=q)
            _objs_artn = object_list.filter(article_number__icontains=q)
            object_list =  _objs_name | _objs_artn
        return object_list


class IngredientDetail(DetailView):
    model = models.Ingredient
    template_name = 'ingredients/detail.html'


class AddIngredient(CreateView):
    model = models.Ingredient
    template_name = 'ingredients/add.html'
    form_class = IngredientForm


class EditIngredient(UpdateView):
    model = models.Ingredient
    template_name = 'ingredients/edit.html'
    form_class = IngredientForm


class AddRecipe(CreateView):
    queryset = models.Recipe.objects.prefetch_related('ingredients__ingredient')
    template_name = 'recipes/add.html'
    form_class = RecipeForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data[FORMSET_NAME] = IngredientsFormSet(self.request.POST)
        else:
            data[FORMSET_NAME] = IngredientsFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context[FORMSET_NAME]
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)


class EditRecipe(UpdateView):
    queryset = models.Recipe.objects.prefetch_related('ingredients__ingredient')
    template_name = 'recipes/edit.html'
    form_class = RecipeForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data[FORMSET_NAME] = IngredientsFormSet(self.request.POST, instance=self.object)
        else:
            data[FORMSET_NAME] = IngredientsFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context[FORMSET_NAME]
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)

recipes/templates/ingredients/__detail_card.html
{% load static %}

<div class="card bg-ingredient">
  <div class="card-body row">
    <div class="col-md-2">
      <img src="{% static 'images/ingredients.jpg' %}" class="card-img-top" alt="Recipe for {{ r.name }}">
    </div>
    <div class="col-md-8">
      <h5 class="card-title">
        {{ ingredient.name }}
        <span class="float-end">
          <a href="{% url 'ingredient-edit' ingredient.id %}">
            <img src="{% static 'images/edit-icon.png' %}"/>
          </a>
        </span>

      </h5>
      <h6 class="card-subtitle mb-2">
        {% if ingredient.article_number %}
          Article#: {{ ingredient.article_number}}
        {% else %}
          食材
        {% endif %}
      </h6>
      <hr>
      <ul class="list-group list-group-flush">
        {% for unit in ingredient.get_units %}
          <li class="list-group-item bg-ingredient">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">¥ {{ unit.cost }}</h5>
              <small>每 {{ unit.unit }}</small>
            </div>
          </li>
        {% endfor %}
        <li class="list-group-item bg-ingredient">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ ingredient.xukezheng }}</h5>
            <small>许可证</small>
          </div>
        </li>
        <li class="list-group-item bg-ingredient">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ ingredient.biaozhun }}</h5>
            <small>标准号</small>
          </div>
        </li>
        <li class="list-group-item bg-ingredient">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ ingredient.baozhi }}</h5>
            <small>保质期</small>
          </div>
        </li>
        <li class="list-group-item bg-ingredient">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ ingredient.chandi }}</h5>
            <small>产地</small>
          </div>
        </li>
        <li class="list-group-item bg-ingredient">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ ingredient.chengfen }}</h5>
            <small>成分</small>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

recipes/templates/ingredients/add.html
{% extends 'layout/_layout_form.html' %}

{% load crispy_forms_tags %}

{% block title %}增加食材{% endblock %}

{% block form %}
  <form method="post">{% csrf_token %}
    <p class="lead">增加食材</p>
    {{ form|crispy }}
    <input class="form-control btn-primary bg-rm-main my-4" type="submit" value="增加食材">
  </form>
{% endblock %}

recipes/templates/ingredients/detail.html
{% extends 'layout/_layout.html' %}

{% block title %}{{ ingredient.name }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col">
      {% include 'ingredients/__detail_card.html' %}
    </div>
  </div>
{% endblock %}

recipes/templates/ingredients/edit.html
{% extends 'layout/_layout_form.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit | {{ ingredient.name }}{% endblock %}

{% block form %}
  <form method="post">{% csrf_token %}
    <p class="lead mb-5">Edit ingredient</p>
    {{ form|crispy }}
    <input class="form-control btn-primary bg-rm-main my-4" type="submit" value="Save">
  </form>
{% endblock %}

recipes/templates/ingredients/list.html
{% extends 'layout/_layout.html' %}
{% load static %}

{% block title %}Ingredients{% endblock %}

{% block content %}
  <div class="row pt-5">
    {% if ingredient_list  %}
      <form class="input-group mb-3" method="get">
        <span class="input-group-text">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </span>
        <input value="{{ request.GET.q }}" name="q" type="text" class="form-control" placeholder="通过名字或编号来搜索食材">
      </form>
      {% for ingredient in ingredient_list %}
      <div class="col-md-4 pt-4">
        {% include 'ingredients/__detail_card.html' %}
      </div>
      {% endfor %}
    {% else %}

    {% if request.GET.q %}
      <p class="lead">No ingredients found matching {{ request.GET.q }}. <a href="{% url 'ingredients' %}">Back to all ingredients</a>.</p>
    {% else %}
    <p class="lead">No ingredients have been added. Add an <a href="{% url 'ingredient-add' %}">ingredient</a></p>
    {% endif %}

    {% endif %}
  </div>
{% endblock %}